-- SGFP — MODELO FISICO V1 SIMPLIFICADO
-- Revisao: 14/09/2026
-- MySQL/MariaDB + WordPress
--
-- Identidade/autenticacao: wp_users.
-- Cada usuario possui exatamente uma CONTA_FINANCEIRA.
-- Saldo e derivado de LANCAMENTO_FINANCEIRO ativo.
-- TRANSFERENCIA e Patrimonio Total estao fora da V1.

DROP TABLE IF EXISTS LANCAMENTO_FINANCEIRO;
DROP TABLE IF EXISTS COMPROMISSO_FINANCEIRO;
DROP TABLE IF EXISTS RECORRENCIA;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS CONTA_FINANCEIRA;

CREATE TABLE CONTA_FINANCEIRA (
    ID_CONTA BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FK_ID_USUARIO BIGINT UNSIGNED NOT NULL,
    NOME VARCHAR(120) NOT NULL DEFAULT 'Minha Conta',
    CRIADA_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_CONTA_USUARIO
        FOREIGN KEY (FK_ID_USUARIO) REFERENCES wp_users(ID),

    CONSTRAINT UQ_CONTA_USUARIO UNIQUE (FK_ID_USUARIO),
    CONSTRAINT UQ_CONTA_ID_USUARIO UNIQUE (ID_CONTA, FK_ID_USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CATEGORIA (
    ID_CATEGORIA BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FK_ID_USUARIO BIGINT UNSIGNED NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CRIADA_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_CATEGORIA_USUARIO
        FOREIGN KEY (FK_ID_USUARIO) REFERENCES wp_users(ID),
    CONSTRAINT UQ_CATEGORIA_NOME_USUARIO UNIQUE (FK_ID_USUARIO, NOME),
    CONSTRAINT UQ_CATEGORIA_ID_USUARIO UNIQUE (ID_CATEGORIA, FK_ID_USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE RECORRENCIA (
    ID_RECORRENCIA BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FK_ID_USUARIO BIGINT UNSIGNED NOT NULL,
    INICIO_MES DATE NOT NULL,
    QUANTIDADE_MESES SMALLINT UNSIGNED,
    ENCERRADA_NO_MES DATE,
    CRIADA_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_RECORRENCIA_USUARIO
        FOREIGN KEY (FK_ID_USUARIO) REFERENCES wp_users(ID),
    CONSTRAINT CK_RECORRENCIA_INICIO_MES CHECK (DAY(INICIO_MES)=1),
    CONSTRAINT CK_RECORRENCIA_QUANTIDADE
        CHECK (QUANTIDADE_MESES IS NULL OR QUANTIDADE_MESES > 0),
    CONSTRAINT CK_RECORRENCIA_ENCERRAMENTO_MES
        CHECK (ENCERRADA_NO_MES IS NULL OR DAY(ENCERRADA_NO_MES)=1),
    CONSTRAINT CK_RECORRENCIA_ENCERRAMENTO_DATA
        CHECK (ENCERRADA_NO_MES IS NULL OR ENCERRADA_NO_MES >= INICIO_MES),
    CONSTRAINT UQ_RECORRENCIA_ID_USUARIO UNIQUE (ID_RECORRENCIA, FK_ID_USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE COMPROMISSO_FINANCEIRO (
    ID_COMPROMISSO BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FK_ID_USUARIO BIGINT UNSIGNED NOT NULL,
    FK_ID_CATEGORIA BIGINT UNSIGNED,
    FK_ID_RECORRENCIA BIGINT UNSIGNED,
    NOME VARCHAR(180) NOT NULL,
    VALOR DECIMAL(14,2) NOT NULL,
    NATUREZA VARCHAR(7) NOT NULL,
    MES_REFERENCIA DATE NOT NULL,
    STATUS VARCHAR(12) NOT NULL DEFAULT 'PENDENTE',
    CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_COMPROMISSO_USUARIO
        FOREIGN KEY (FK_ID_USUARIO) REFERENCES wp_users(ID),
    CONSTRAINT FK_COMPROMISSO_CATEGORIA
        FOREIGN KEY (FK_ID_CATEGORIA, FK_ID_USUARIO)
        REFERENCES CATEGORIA(ID_CATEGORIA, FK_ID_USUARIO),
    CONSTRAINT FK_COMPROMISSO_RECORRENCIA
        FOREIGN KEY (FK_ID_RECORRENCIA, FK_ID_USUARIO)
        REFERENCES RECORRENCIA(ID_RECORRENCIA, FK_ID_USUARIO),

    CONSTRAINT CK_COMPROMISSO_VALOR CHECK (VALOR >= 0),
    CONSTRAINT CK_COMPROMISSO_NATUREZA CHECK (NATUREZA IN ('ENTRADA','SAIDA')),
    CONSTRAINT CK_COMPROMISSO_MES CHECK (DAY(MES_REFERENCIA)=1),
    CONSTRAINT CK_COMPROMISSO_STATUS
        CHECK (STATUS IN ('PENDENTE','EFETIVADO','EXCLUIDO')),
    CONSTRAINT UQ_COMPROMISSO_RECORRENCIA_MES
        UNIQUE (FK_ID_RECORRENCIA, MES_REFERENCIA),
    CONSTRAINT UQ_COMPROMISSO_ID_USUARIO
        UNIQUE (ID_COMPROMISSO, FK_ID_USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE LANCAMENTO_FINANCEIRO (
    ID_LANCAMENTO BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FK_ID_USUARIO BIGINT UNSIGNED NOT NULL,
    FK_ID_COMPROMISSO BIGINT UNSIGNED,
    FK_ID_CONTA BIGINT UNSIGNED NOT NULL,
    ORIGEM VARCHAR(15) NOT NULL,
    NOME VARCHAR(180) NOT NULL,
    VALOR DECIMAL(14,2) NOT NULL,
    TIPO_EFEITO VARCHAR(7) NOT NULL,
    DATA_EFETIVACAO DATETIME NOT NULL,
    DESCRICAO VARCHAR(500),
    ESTADO VARCHAR(10) NOT NULL DEFAULT 'ATIVO',
    CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DESFEITO_EM DATETIME,

    ID_COMPROMISSO_ATIVO BIGINT UNSIGNED
        GENERATED ALWAYS AS (
            CASE WHEN ORIGEM='COMPROMISSO' AND ESTADO='ATIVO'
                 THEN FK_ID_COMPROMISSO ELSE NULL END
        ) STORED,
    ID_CONTA_COMPROMISSO_ATIVA BIGINT UNSIGNED
        GENERATED ALWAYS AS (
            CASE WHEN ORIGEM='COMPROMISSO' AND ESTADO='ATIVO'
                 THEN FK_ID_CONTA ELSE NULL END
        ) STORED,
    ID_CONTA_SALDO_INICIAL_ATIVO BIGINT UNSIGNED
        GENERATED ALWAYS AS (
            CASE WHEN ORIGEM='SALDO_INICIAL' AND ESTADO='ATIVO'
                 THEN FK_ID_CONTA ELSE NULL END
        ) STORED,

    CONSTRAINT FK_LANCAMENTO_USUARIO
        FOREIGN KEY (FK_ID_USUARIO) REFERENCES wp_users(ID),
    CONSTRAINT FK_LANCAMENTO_COMPROMISSO
        FOREIGN KEY (FK_ID_COMPROMISSO, FK_ID_USUARIO)
        REFERENCES COMPROMISSO_FINANCEIRO(ID_COMPROMISSO, FK_ID_USUARIO),
    CONSTRAINT FK_LANCAMENTO_CONTA
        FOREIGN KEY (FK_ID_CONTA, FK_ID_USUARIO)
        REFERENCES CONTA_FINANCEIRA(ID_CONTA, FK_ID_USUARIO),

    CONSTRAINT CK_LANCAMENTO_ORIGEM
        CHECK (ORIGEM IN ('COMPROMISSO','SALDO_INICIAL')),
    CONSTRAINT CK_LANCAMENTO_ORIGEM_COMPROMISSO CHECK (
        (ORIGEM='COMPROMISSO' AND FK_ID_COMPROMISSO IS NOT NULL AND VALOR >= 0)
        OR
        (ORIGEM='SALDO_INICIAL' AND FK_ID_COMPROMISSO IS NULL)
    ),
    CONSTRAINT CK_LANCAMENTO_TIPO_EFEITO
        CHECK (TIPO_EFEITO IN ('ENTRADA','SAIDA')),
    CONSTRAINT CK_LANCAMENTO_SALDO_INICIAL
        CHECK (ORIGEM <> 'SALDO_INICIAL' OR TIPO_EFEITO='ENTRADA'),
    CONSTRAINT CK_LANCAMENTO_ESTADO
        CHECK (ESTADO IN ('ATIVO','DESFEITO')),
    CONSTRAINT CK_LANCAMENTO_DESFAZIMENTO CHECK (
        (ESTADO='ATIVO' AND DESFEITO_EM IS NULL)
        OR
        (ESTADO='DESFEITO' AND DESFEITO_EM IS NOT NULL)
    ),

    CONSTRAINT UQ_LANCAMENTO_EFEITO_ATIVO
        UNIQUE (ID_COMPROMISSO_ATIVO, ID_CONTA_COMPROMISSO_ATIVA),
    CONSTRAINT UQ_LANCAMENTO_SALDO_INICIAL_ATIVO
        UNIQUE (ID_CONTA_SALDO_INICIAL_ATIVO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Aplicacao:
-- cadastro provisiona uma unica conta "Minha Conta";
-- compromisso criado nao altera saldo;
-- efetivacao cria Lancamento ativo;
-- desfazimento marca o Lancamento como DESFEITO;
-- reset remove dados e reprovisiona conta/categorias;
-- exclusao remove dados SGFP antes de concluir a remocao do login WordPress;
-- FK_ID_USUARIO sempre vem da sessao autenticada.

-- Saldo:
-- SELECT COALESCE(SUM(CASE
--   WHEN TIPO_EFEITO='ENTRADA' THEN VALOR
--   WHEN TIPO_EFEITO='SAIDA' THEN -VALOR
-- END),0)
-- FROM LANCAMENTO_FINANCEIRO
-- WHERE FK_ID_USUARIO=<USUARIO>
--   AND FK_ID_CONTA=<CONTA_UNICA>
--   AND ESTADO='ATIVO';
